import type { Product } from "./catalog-types";

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Raven XR 35 LRF",
    brand: "Raven",
    type: "scope",
    priceRub: 219000,
    matrix: "640×512",
    lensMm: 35,
    magnificationMin: 1.6,
    magnificationMax: 6.4,
    hasRangefinder: true,
    inStock: true,
    popularity: 92,
  },
  {
    id: "p2",
    name: "Raven XR 50",
    brand: "Raven",
    type: "scope",
    priceRub: 199000,
    matrix: "640×512",
    lensMm: 50,
    magnificationMin: 2.0,
    magnificationMax: 8.0,
    hasRangefinder: false,
    inStock: true,
    popularity: 79,
  },
  {
    id: "p3",
    name: "Kestrel M19 Compact",
    brand: "Kestrel",
    type: "monocular",
    priceRub: 59000,
    matrix: "384×288",
    lensMm: 19,
    magnificationMin: 1.0,
    magnificationMax: 4.0,
    hasRangefinder: false,
    inStock: true,
    popularity: 65,
  },
  {
    id: "p4",
    name: "Kestrel M25 Pro",
    brand: "Kestrel",
    type: "monocular",
    priceRub: 99000,
    matrix: "384×288",
    lensMm: 25,
    magnificationMin: 1.2,
    magnificationMax: 4.8,
    hasRangefinder: false,
    inStock: false,
    popularity: 71,
  },
  {
    id: "p5",
    name: "Vanguard V35 LRF",
    brand: "Vanguard",
    type: "scope",
    priceRub: 279000,
    matrix: "640×512",
    lensMm: 35,
    magnificationMin: 2.0,
    magnificationMax: 8.0,
    hasRangefinder: true,
    inStock: true,
    popularity: 88,
  },
  {
    id: "p6",
    name: "Vanguard V50 Ultra",
    brand: "Vanguard",
    type: "scope",
    priceRub: 319000,
    matrix: "1024×768",
    lensMm: 50,
    magnificationMin: 2.5,
    magnificationMax: 10,
    hasRangefinder: false,
    inStock: true,
    popularity: 77,
  },
  {
    id: "p7",
    name: "Sentinel S35 1280",
    brand: "Sentinel",
    type: "scope",
    priceRub: 499000,
    matrix: "1280×1024",
    lensMm: 35,
    magnificationMin: 2.0,
    magnificationMax: 12,
    hasRangefinder: true,
    inStock: false,
    popularity: 83,
  },
  {
    id: "p8",
    name: "Sentinel Mono 50 LRF",
    brand: "Sentinel",
    type: "monocular",
    priceRub: 189000,
    matrix: "640×512",
    lensMm: 50,
    magnificationMin: 2.0,
    magnificationMax: 8.0,
    hasRangefinder: true,
    inStock: true,
    popularity: 74,
  },
  {
    id: "p9",
    name: "Nomad M35",
    brand: "Nomad",
    type: "monocular",
    priceRub: 149000,
    matrix: "640×512",
    lensMm: 35,
    magnificationMin: 1.5,
    magnificationMax: 6.0,
    hasRangefinder: false,
    inStock: true,
    popularity: 69,
  },
  {
    id: "p10",
    name: "MM06-50 LRF",
    brand: "Sytong",
    type: "scope",
    priceRub: 179000,
    matrix: "640×512",
    lensMm: 50,
    magnificationMin: 2.0,
    magnificationMax: 8.0,
    hasRangefinder: true,
    inStock: true,
    popularity: 96,
  },
];

